---
- name: Remove users 1 to 1000
  hosts: dev_server
  become: true
  vars:
    number_of_users: 1000

  tasks:
    - name: 'remove user'
      command: userdel -r "user{{ item }}"
      with_sequence: start=1 end={{ number_of_users }} format=user%d
